# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json

defaults:
  # override the terminal font size when in windows or when using sixel.
  terminal_font_size: 2
